Repository ecto0310/sit_graduation_checker, pull requests merged in 2022-10, with the labels that each got.

#9 Feature Cloudflare analytics
  public/index.html
Labels: feature

#12 Feature complex condition
  public/rule/al21_graduation.json
  public/rule/al21_research_start.json
  src/Components/CheckCreditRule.tsx
  src/Components/CheckGradePointAverageRule.tsx
  src/Components/CheckResultRule.tsx
  src/Components/CheckRule.tsx
  src/Components/Evaluation.tsx
  src/Components/LoadRule.tsx
Labels: feature

#13 Document readme
  README.md
  sample.png
Labels: document

#14 Feature global limit
  README.md
  src/Components/CheckCreditRule.tsx
  src/Components/LoadRule.tsx
Labels: feature

#11 Feature bv21 graduation rule
  public/rule/bv21_graduation.json
  public/rule/rule.json
Labels: feature

#15 Fix shortage count
  src/Components/CheckCreditRule.tsx
Labels: fix

#16 Feature auto create list
  .gitignore
  README.md
  create_rule_list.sh
  package.json
  public/rule/al21_research_start.json
  public/rule/rule.json
  src/Components/LoadRule.tsx
Labels: feature

#17 Feature subject count
  README.md
  src/Components/CheckCreditRule.tsx
  src/Components/CheckRule.tsx
  src/Components/LoadRule.tsx
Labels: feature

#18 Feature fontawesome
  package.json
  src/Components/CheckCreditRule.tsx
  src/Components/CheckGradePointAverageRule.tsx
  src/Components/CheckMark.tsx
  src/Components/CheckResultRule.tsx
  yarn.lock
Labels: feature

#19 Document readme
  README.md
  sample.png
Labels: document
